### ISSUE TITLE
Restructize things to integrate with pmOS and other distros

### ISSUE THREAD

**Issue by akemnade** [bjesus/air#2]
Something like a full ui/session/desktop package including deps, maybe as a first step without koreader, would probably be nice, so you can directly choose it in pmbootstrap init
so e.g. some postmarketos-ui-air package or something

**Comment by bjesus** [comment]
Yes this in undoubtedly something I want to do. I have no idea where to start - will look it up. I think it could be a challenge to make AIR not Kobo Clara specific, but possible.

**Comment by akemnade** [comment]
having things kobo clara specific: 
Well, lets look around:
batterystatus = awful.widget.watch(
  "bash -c \"upower -i /org/freedesktop/UPower/devices/battery_rn5t618_battery | grep -E 'state|percent' | awk '{print $2}' | tac | tr '\n' ' '\"",
  30
)
ok, there is a path, but other applications manage it just automatically to display battery status. On my laptops I had never problems with that.
So a bit looking around for doing it the best way. And Illume (former mobile surface for enlightenment) did it too.

Warm/Cold slider: check for presence of the corresponding backlight,
if not available, add any backlight found as a slider.

Kicking the touchpad after suspend... I think that should be fixed in kernel.

Rotating input in combination with display. I am wondering whether something is ready somewhere... Some other uis manage to do this somehow.

Towards the full ui selection thing: maybe first install it systemwide.
Then create an APKBUILD file pointing to your repo inspired by other postmarketos-ui-something packagges.

**Comment by m040601** [comment]
Do any of you guys have an account or contribute to the PostmarketOS wiki ?

Put your name there in "Users owning this device", https://wiki.postmarketos.org/wiki/Kobo_Clara_HD_(kobo-clara)

I cant see any mention or pointer to "Air" from the PostmarketOS wiki.

It would sure benefit everyone if what's being discussed here had at least a link from there.
So that anyone with a Kobo visiting PostmarketOS at least knows "Air" exists.


Another essential place to announce this project is, https://www.mobileread.com/forums/ , maybe the "Kobo Devices" page, https://www.mobileread.com/forums/forumdisplay.php?s=111c3eea4a4353d2dad5a871f4fc1c13&f=223 . Or "Kobo Developers Corner" , https://www.mobileread.com/forums/forumdisplay.php?f=247  It is not Koreader specific. 


---- EDIT ----

Correction.

I now see that there is in fact mention of Air there, https://wiki.postmarketos.org/wiki/Kobo_Clara_HD_(kobo-clara)


> Recommended - a set of customized scripts for AwesomeWM, the author uses them on a Clara HD. See [here](https://github.com/bjesus/air)

**Comment by akemnade** [comment]
There is also https://wiki.postmarketos.org/wiki/Using_ebook_reader_hardware

BTW: There are also other ebook readers supported by pmOS.
The Tolino Shine 3 should be supported equally well by Air

**Comment by bjesus** [comment]
It seems like there is some kernel work being done that perhaps removes the need for my workaround for making the touchscreen resume from suspend properly: https://lore.kernel.org/lkml/20230501113010.891786-1-mweigand@mweigand.net/T/#u 

I'm not sure if it was merged already and if so on what release it will be included 🤔

@akemnade you're right - all these things should be solvable. I'll try to generalize the code so it won't be so Clara-specific.

**Comment by chloe-everhart** [comment]
Hi, I'm grateful for what you've done.  

I want to get rid of an LED monitor and just use an eink monitor for my desktop as soon as I can get one.  

I'd love to see this  ported to x86_64.

If it's ported to x86_64 it would help if it included a Night Color setting for normal LED screens, because that's an accessibility feature for me and would let me try it out while I still have an LED screen.

Is there anything I can do to help make that happen, despite having end user level tech skills?

**Comment by chloe-everhart** [comment]
Maybe there would be a way to set 0-255 on the blue, green, and red LEDs if it was on x86_64?
